#Spring configuration
spring:
  main:
    allow-bean-definition-overriding: true
  #MongoDB config
  data:
    mongodb:
      database: db
      uri: mongodb://guillermo:Vly8emxhxxDhTPKoHHYvC169z0YX2IO3R0NIDggriEXLswTrLU6ttwUEwsb495NKernmoa12T5gfizOXbRawlA==@guillermo.documents.azure.com:10255/?ssl=true&replicaSet=globaldb

#Sofia2 config
onesaitplatform:
  iotclient:
    urlRestIoTBroker: https://s4citiespro.westeurope.cloudapp.azure.com/iot-broker
    sslverify: true
    token: 724fcaba296742cba85e2a92357d8d86
    deviceTemplate: EtsisiApp
    device: instance1
    connectTimeoutInSec: 10
    writeTimeoutInSec: 30
    readTimeoutInSec: 30