#Spring configuration
spring:
  main:
    allow-bean-definition-overriding: true
  #MongoDB config
  data:
    mongodb:
      database: 
      uri: 
#Sofia2 config
onesaitplatform:
  iotclient:
    urlRestIoTBroker: 
    sslverify: 
    token: 
    deviceTemplate: 
    device: 
    connectTimeoutInSec: 10
    writeTimeoutInSec: 30
    readTimeoutInSec: 30